# Generated by Django 2.1.2 on 2018-10-27 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertracking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wastetracking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
